---
abstract: 'LWP::UserAgent subclass for a CAS aware UserAgent'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.112150'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Authen-CAS-UserAgent
provides:
  Authen::CAS::UserAgent:
    file: lib/Authen/CAS/UserAgent.pm
    version: v1.0.0
requires:
  Exporter: 0
  HTTP::Message: 0
  LWP::UserAgent: 0
  URI: 0
  XML::LibXML: 0
resources:
  license: http://opensource.org/licenses/mit-license.php
version: v1.0.0
